### ISSUE TITLE
Syntastic Error

### ISSUE THREAD

**Issue by wildtype** [KMK-ONLINE/vim-config#7]
We got this error messages when saving js file:

```
"spec/javascripts/bbmoauth_spec.js" 30L, 695C written
syntastic: error: checker output:
/home/woi/.rvm/gems/ruby-2.3.1/gems/jshint-1.5.0/lib/jshint/cli.rb:6:in `const_get': wrong constant name --verbose (NameError)
^Ifrom /home/woi/.rvm/gems/ruby-2.3.1/gems/jshint-1.5.0/lib/jshint/cli.rb:6:in `run'
^Ifrom /home/woi/.rvm/gems/ruby-2.3.1/gems/jshint-1.5.0/bin/jshint:12:in `<top (required)>'
^Ifrom /home/woi/.rvm/gems/ruby-2.3.1/bin/jshint:23:in `load'
^Ifrom /home/woi/.rvm/gems/ruby-2.3.1/bin/jshint:23:in `<main>'
^Ifrom /home/woi/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
^Ifrom /home/woi/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
syntastic: error: checker javascript/jshint returned abnormal status 1 
```

Anyone know how to solve, or maybe we can just turn of syntastic for js? How?

**Comment by wildtype** [comment]
Solved:
```
sudo gem uninstall jshint
sudo npm install -g jshint
```

This happens because syntastic execute `jshint`, expecting jshint from npm. Meanwhile in our system `jshint` command refer to jshint from rubygems.
